### ISSUE TITLE
Can't bind to 'TreeData' since it isn't a known property of 'resource-tree-view'.

### ISSUE THREAD

**Issue by praveen-vishnu** [missakation/IonicTreeView#1]
@missakation
 **I have Followed your "readme" file.** Still Getting this error
```

Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'TreeData' since it isn't a known property of 'resource-tree-view'.
1. If 'resource-tree-view' is an Angular component and it has 'TreeData' input, then verify that it is part of this module.
2. If 'resource-tree-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<ion-content >
  <resource-tree-view [ERROR ->][TreeData]="Family" [hasCheckbox]="true"></resource-tree-view>
</ion-content>
"): ng:///GenealogyPageModule/GenealogyPage.html@31:22
Can't bind to 'hasCheckbox' since it isn't a known property of 'resource-tree-view'.
1. If 'resource-tree-view' is an Angular component and it has 'hasCheckbox' input, then verify that it is part of this module.
2. If 'resource-tree-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
```
The ERROR Quite Big i have pasted half of it
Help Me Out Here
Thank You

**Comment by missakation** [comment]
I think you are missing something. Just clone and ionic serve and see how things are done. You may have changed variable names and forgot to change other places like TreeData

**Comment by praveen-vishnu** [comment]
Actually I first Cloned your repo it's working fine .. but when i included in my existing ionic application then its showing the ERROR

**Comment by missakation** [comment]
Ye. You're missing something or copy pasting wrong or have wrong variable names. Read and understand well how components work

**Comment by asclepius76** [comment]
i know it's been a while, but , i had the same error, but it was due to lazy loading, if that's your case, remove the import from app.module.ts and import it in your page, i.e., your_page.module.ts.

**Comment by praveen-vishnu** [comment]
@asclepius76  Well thank you  That Worked For Me..

**Comment by praveen-vishnu** [comment]
@missakation and @asclepius76   Thankyou For your Involvement In This Issue
